In [12]:
# Visualização dos dados de entrada
import pandas as pd
arq = './dados/pubmed-rct-20k.parquet'
df = pd.read_parquet(arq)
df = df[(df['split'] == 'dev') & (df['split'] == 'dev')]
df[df['pmid'] <= '24252935']
#df[(df['integra'] == '') & (df['fold'] == 12)]
#df

#df

,pmid,article,split,response
0,24219891,"Plasminogen activator inhibitor-1, monocyte ch...",dev,"{'background': '', 'conclusions': 'Temporary h..."
1,24220044,Training in methods of preventing childhood ob...,dev,"{'background': '', 'conclusions': 'Training in..."
2,24220504,Golden plaster for pain therapy in patients wi...,dev,{'background': 'Osteoarthritis is a relatively...
3,24220704,Reference range for the antimüllerian hormone ...,dev,"{'background': '', 'conclusions': 'Age-specifi..."
4,24220935,Circulating proteins as potential biomarkers o...,dev,"{'background': '', 'conclusions': 'Our finding..."
5,24225201,Clinical profiles and outcomes in patients wit...,dev,{'background': 'Heart failure ( HF ) and chron...
6,24225216,[Clinical significance of dynamic monitoring o...,dev,"{'background': '', 'conclusions': 'Dynamic mon..."
7,24225356,Linear growth increased in young children in a...,dev,{'background': 'Haiti has experienced rapid ur...
8,24225379,Visual outcome of patients following NAION aft...,dev,"{'background': '', 'conclusions': 'This is the..."
9,24225740,Effects of antioxidant supplementation on exer...,dev,"{'background': '', 'conclusions': 'Aerobic exe..."
10,24226381,Prophylaxis of intra- and postoperative nausea...,dev,{'background': 'This paper describes a randomi...
11,24226808,High-sensitivity troponin I for risk assessmen...,dev,{'background': 'High-sensitivity troponin-I ( ...
12,24228532,"[Multi-centered, randomized controlled clinica...",dev,"{'background': '', 'conclusions': 'Integrated ..."
13,24228533,[Randomized controlled study of integrated tre...,dev,"{'background': '', 'conclusions': 'The integra..."
14,24228534,[Intervention of immune 1 combined HAART on im...,dev,"{'background': '', 'conclusions': 'Immune 1 co..."
15,24228747,The spinal stenosis pedometer and nutrition li...,dev,"{'background': 'Because of symptoms , people w..."
16,24229360,Azithromycin and cough-specific health status ...,dev,{'background': 'Macrolides reduce exacerbation...
17,24229362,Study protocol: Rehabilitation including Socia...,dev,{'background': 'During cancer treatment childr...
18,24229754,Efficacy and safety of desvenlafaxine 50 mg/d ...,dev,{'background': 'ClinicalTrials.gov identifier ...
19,24231400,Impact of physical exercise on reaction time i...,dev,"{'background': '', 'conclusions': 'Supervised ..."
20,24231627,Docetaxel or pemetrexed with or without cetuxi...,dev,{'background': 'Available preclinical and phas...
21,24231639,"Higher protein intake improves length, not wei...",dev,"{'background': '', 'conclusions': 'Higher cumu..."
22,24232133,Minimally invasive surgery training using mult...,dev,{'background': 'Structural learning theory sug...
23,24232362,A randomized feasibility study of a 12-week co...,dev,"{'background': '', 'conclusions': 'Observed ef..."
24,24232445,The impact of missing data on clinical trials:...,dev,"{'background': '', 'conclusions': 'There is no..."
25,24233244,The effects of aerobic exercise training at tw...,dev,"{'background': '', 'conclusions': 'Exercise tr..."
26,24236828,Efficacy and safety of low-dose otelixizumab a...,dev,"{'background': '', 'conclusions': 'Efficacy an..."
27,24237188,Purified dry extract of Paullinia cupana (guar...,dev,"{'background': '', 'conclusions': 'We conclude..."
28,24239154,"One-year results of the randomized, controlled...",dev,{'background': 'Previous studies on cognitive ...
29,24239202,5-year results of a randomized comparison of X...,dev,{'background': 'The use of EES compared to PES...
30,24239210,"Fluorouracil, epirubicin, and cyclophosphamide...",dev,{'background': 'Neoadjuvant chemotherapy with ...
31,24239213,"Pharmacist, general practitioner and consumer ...",dev,{'background': 'Providing written medicine inf...
32,24240354,Corneal inflammatory events with daily silicon...,dev,"{'background': '', 'conclusions': 'The probabi..."
33,24240384,Alpha lipoic acid attenuates inflammatory resp...,dev,"{'background': '', 'conclusions': 'Our finding..."
34,24240611,Mechanical chest compressions and simultaneous...,dev,{'background': 'clinicaltrials.gov Identifier ...
35,24241327,An estimate of hernia prevalence in Sierra Leo...,dev,"{'background': '', 'conclusions': 'The results..."
36,24245738,Early accelerated senescence of circulating en...,dev,{'background': 'The decreased number and senes...
37,24245844,Preformulated implementation intentions to pro...,dev,"{'background': '', 'conclusions': 'Preformulat..."
38,24245880,Rejuvenation effects of hyaluronic acid inject...,dev,{'background': 'Pronounced nasojugal groove ( ...
39,24246119,[Moderate potentially drug-induced hyponatremi...,dev,"{'background': '', 'conclusions': 'This study ..."
40,24246588,Effect of an intervention to improve the cardi...,dev,{'background': 'Family members of patients wit...
41,24247211,Differential effects of FODMAPs (fermentable o...,dev,"{'background': '', 'conclusions': 'Fructose bu..."
42,24247300,Low-dose dopamine or low-dose nesiritide in ac...,dev,{'background': 'clinicaltrials.gov Identifier ...
43,24247476,The glucoregulatory benefits of glucagon-like ...,dev,"{'background': '', 'conclusions': 'Glucagon-li..."
44,24247812,A pharmacokinetic and pharmacodynamic comparis...,dev,{'background': 'Previous metoprolol studies in...
45,24248037,A randomized controlled trial to assess adhere...,dev,{'background': 'Short message service ( SMS ) ...
46,24248549,The effect of two different trochanteric nail ...,dev,"{'background': '', 'conclusions': 'Both design..."
47,24249049,Cardiac structure and function in heart failur...,dev,{'background': 'Heart failure with preserved e...
48,24249434,Additive postprandial glucose-lowering effects...,dev,{'background': 'The aim of this research was t...
49,24249853,A scale to measure pharmacy students' self-eff...,dev,"{'background': '', 'conclusions': '', 'journal..."
50,24251386,Cost-effectiveness of tooth replacement strate...,dev,"{'background': '', 'conclusions': 'With an inc..."
51,24252596,Copenhagen study of overweight patients with c...,dev,{'background': 'Coronary artery disease ( CAD ...
52,24252663,Comparing in-person to videoconference-based c...,dev,{'background': 'Cognitive-behavioral therapy (...

In [7]:
# Visualização dos dados de entrada
import pandas as pd
arq = './saidas/saida_pubmed_prof.parquet'
df = pd.read_parquet(arq)

df

          chave resumo                                           resposta erro
0      24219891     {}  {"background": "", "conclusions": "Temporary h...
1      24220044     {}  {"background": "", "conclusions": "Training in...
2      24220504     {}  {"background": "Osteoarthritis is a relatively...
3      24220704     {}  {"background": "", "conclusions": "Age-specifi...
4      24220935     {}  {"background": "", "conclusions": "Our finding...
...         ...    ...                                                ...  ...
19990  26521572     {}  {"background": "", "conclusions": "The simulta...
19991  26521581     {}  {"background": "", "conclusions": "Acupuncture...
19992  26521582     {}  {"background": "", "conclusions": "The clinica...
19993  26521589     {}  {"background": "", "conclusions": "EA at Neigu...
19994  26529159     {}  {"background": "clinicaltrials.gov Identifier ...

[19995 rows x 4 columns]

In [3]:
from util_pubmed import enrich_abstract
enrich_abstract(24228747)

Env encontrado em ../../src/.env

{'pmid': '24228747',
 'titulo': 'The spinal stenosis pedometer and nutrition lifestyle intervention (SSPANLI) randomized controlled trial protocol.',
 'palavras_chave': [],
 'journal': 'BMC musculoskeletal disorders',
 'data_publicacao': '2013-Nov'}