In [2]:
# Visualização dos dados de entrada
import pandas as pd
arq = './dados/pubmed-rct-20k.parquet'
df = pd.read_parquet(arq)
df = df[(df['split'] == 'test') ]
df[df['pmid'] <= '24252935']
#df[(df['integra'] == '') & (df['fold'] == 12)]
#df

#df

,pmid,article,split,response
2499,24220007,Comparative effectiveness of 3-dimensional vs ...,test,{'background': 'Although the potential benefit...
2500,24220099,Results of a randomized controlled trial to pr...,test,"{'background': '', 'conclusions': 'A relativel..."
2501,24220161,The impact of prenatal vitamin A and zinc supp...,test,{'background': 'Prenatal supplementation with ...
2502,24220547,Adolescent depressive disorders and family bas...,test,{'background': 'There is increasing community ...
2503,24220913,Postdiagnosis C-reactive protein and breast ca...,test,{'background': 'Serum C-reactive protein ( CRP...
2504,24222508,The relation between social support and smokin...,test,{'background': 'Although social support is an ...
2505,24225010,Spinal manipulative therapy and exercise for s...,test,"{'background': 'Neck pain , common among the e..."
2506,24225081,Porvoo sarcopenia and nutrition trial: effects...,test,{'background': 'Age-related muscle loss ( that...
2507,24225149,Diabetes self-management smartphone applicatio...,test,{'background': 'Persistently poor glycemic con...
2508,24225780,Photodynamic therapy to treat periimplantitis....,test,"{'background': '', 'conclusions': 'Total anaer..."
2509,24226490,Influence of LMA cuff pressure on the incidenc...,test,{'background': 'Pharyngolaryngeal discomfort i...
2510,24228683,"The impact of school water, sanitation, and hy...",test,"{'background': '', 'conclusions': 'In water-sc..."
2511,24228935,Reflecting on the methodological challenges of...,test,{'background': 'Successful recruitment of part...
2512,24229434,Extraperitoneal laparoscopic adenomectomy (Mad...,test,"{'background': '', 'conclusions': 'Compared wi..."
2513,24229729,Does peer learning or higher levels of e-learn...,test,"{'background': '', 'conclusions': 'This study ..."
2514,24229753,A gender analysis of the study of pharmacother...,test,{'background': 'Gender differences exist in ps...
2515,24231013,Influence of early enteral nutrition (EEN) on ...,test,"{'background': '', 'conclusions': 'The managem..."
2516,24231226,Declining cognition and falls: role of risky p...,test,{'background': 'Declining cognition is a risk ...
2517,24231777,Rapid sensitive molecular diagnosis of pyogeni...,test,{'background': 'Rapid diagnosis and accurate d...
2518,24232052,Peroral endoscopic myotomy for idiopathic acha...,test,{'background': 'Peroral endoscopic myotomy ( P...
2519,24232665,Bach music in preterm infants: no 'Mozart effe...,test,"{'background': '', 'conclusions': 'Mozart musi..."
2520,24235064,Effects of supervised exercise program on meta...,test,{'background': 'Inactivity is a primary factor...
2521,24237724,Efficacy of aloe vera gel as an adjuvant treat...,test,"{'background': '', 'conclusions': 'Aloe vera g..."
2522,24237751,Is topical zinc effective in the treatment of ...,test,"{'background': '', 'conclusions': 'Topical zin..."
2523,24237999,Remission in rheumatoid arthritis patients tre...,test,"{'background': '', 'conclusions': 'Remission b..."
2524,24238630,Effectiveness of a web-based treatment program...,test,{'background': 'Disordered eating behavior and...
2525,24238679,The effect of primary care interventions on ch...,test,"{'background': '', 'conclusions': 'Brief prima..."
2526,24238770,Contrasting breathing retraining and helium-ox...,test,{'background': 'Breathing-retraining and heliu...
2527,24238862,"A phase II/III, multicenter, safety, efficacy,...",test,"{'background': '', 'conclusions': 'Dexmedetomi..."
2528,24239341,Randomized clinical trial of an emergency depa...,test,"{'background': '', 'conclusions': 'An ED obser..."
2529,24239386,Quality of survival and growth in children and...,test,"{'background': '', 'conclusions': 'Hyperfracti..."
2530,24239662,Impact of smoking on long-term outcomes in pat...,test,{'background': 'Smoking enhances clopidogrel-i...
2531,24239841,Phased RF ablation in persistent atrial fibril...,test,{'background': 'Persistent and long-standing p...
2532,24240244,Two low-dose levonorgestrel intrauterine contr...,test,"{'background': 'ClinicalTrials.gov , www.clini..."
2533,24240351,The effect of caffeine on tear secretion.\n\nC...,test,"{'background': '', 'conclusions': 'From our st..."
2534,24240647,A pilot phase II RCT of a home-based exercise ...,test,{'background': 'Fatigue is the most common and...
2535,24241095,Effect of omega-3 supplementation on serum lev...,test,{'background': 'Patients with end-stage renal ...
2536,24245491,Integrated care for comorbid alcohol dependenc...,test,{'background': 'A major barrier to successful ...
2537,24245807,Prediction of symptomatic improvement after ex...,test,{'background': 'Several studies show that psyc...
2538,24246210,"A randomised, double-blind, parallel design, m...",test,"{'background': '', 'conclusions': 'Imidafenaci..."
2539,24246378,Relation of the International Restless Legs Sy...,test,{'background': 'The SP790 study ( ClinicalTria...
2540,24246711,Comparison of the outcome of conventional in v...,test,"{'background': '', 'conclusions': 'Couples wit..."
2541,24249542,Effect of preoperative pelvic floor muscle the...,test,"{'background': '', 'conclusions': 'Preoperativ..."
2542,24249695,Randomised controlled trial of early frenotomy...,test,"{'background': '', 'conclusions': 'Early freno..."
2543,24249817,Probiotic effects on late-onset sepsis in very...,test,"{'background': '', 'conclusions': 'The probiot..."
2544,24250307,Impact of weight loss on markers of systemic i...,test,{'background': 'Weight loss studies were condu...
2545,24252418,Vitamin A supplementation and risk of atopy: l...,test,{'background': 'The World Health Organization ...
2546,24252714,Motivational interviewing and intimate partner...,test,"{'background': '', 'conclusions': 'With a lowe..."
2547,24252844,The peroxisome proliferator activated receptor...,test,{'background': 'Rheumatoid arthritis ( RA ) is...

In [7]:
# Visualização dos dados de entrada
import pandas as pd
arq = './saidas/saida_pubmed_prof.parquet'
df = pd.read_parquet(arq)

df

          chave resumo                                           resposta erro
0      24219891     {}  {"background": "", "conclusions": "Temporary h...
1      24220044     {}  {"background": "", "conclusions": "Training in...
2      24220504     {}  {"background": "Osteoarthritis is a relatively...
3      24220704     {}  {"background": "", "conclusions": "Age-specifi...
4      24220935     {}  {"background": "", "conclusions": "Our finding...
...         ...    ...                                                ...  ...
19990  26521572     {}  {"background": "", "conclusions": "The simulta...
19991  26521581     {}  {"background": "", "conclusions": "Acupuncture...
19992  26521582     {}  {"background": "", "conclusions": "The clinica...
19993  26521589     {}  {"background": "", "conclusions": "EA at Neigu...
19994  26529159     {}  {"background": "clinicaltrials.gov Identifier ...

[19995 rows x 4 columns]

In [6]:
# Visualização dos dados de entrada
import pandas as pd
arq = './saidas/saida_pubmed_1_5b(c)_teste.parquet'
df = pd.read_parquet(arq)
df

,chave,resumo,resposta,erro
0,24772594,"{""prompt_tokens"": 614, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
1,24773166,"{""prompt_tokens"": 805, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
2,24773567,"{""prompt_tokens"": 712, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
3,24774260,"{""prompt_tokens"": 642, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
4,24774351,"{""prompt_tokens"": 615, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
...,...,...,...,...
2495,24769399,"{""prompt_tokens"": 690, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
2496,24769601,"{""prompt_tokens"": 607, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
2497,24770694,"{""prompt_tokens"": 677, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
2498,24771706,"{""prompt_tokens"": 665, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta
2499,24772412,"{""prompt_tokens"": 552, ""completion_tokens"": 40...",!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!...,Não foi possível extrair JSON da resposta

In [3]:
from util_pubmed import enrich_abstract
enrich_abstract(24228747)

Env encontrado em ../../src/.env

{'pmid': '24228747',
 'titulo': 'The spinal stenosis pedometer and nutrition lifestyle intervention (SSPANLI) randomized controlled trial protocol.',
 'palavras_chave': [],
 'journal': 'BMC musculoskeletal disorders',
 'data_publicacao': '2013-Nov'}