In [1]:
# Visualização dos dados de entrada
import pandas as pd
arq = './dados/pubmed-rct-20k.parquet'
df = pd.read_parquet(arq)
#df[df['fold'] == 12]
#df[(df['integra'] == '') & (df['fold'] == 12)]
#df

df

,pmid,article,split,response
0,24219891,"Plasminogen activator inhibitor-1, monocyte ch...",dev,"{'background': '', 'conclusions': 'Temporary h..."
1,24220044,Training in methods of preventing childhood ob...,dev,"{'background': '', 'conclusions': 'Training in..."
2,24220504,Golden plaster for pain therapy in patients wi...,dev,{'background': 'Osteoarthritis is a relatively...
3,24220704,Reference range for the antimüllerian hormone ...,dev,"{'background': '', 'conclusions': 'Age-specifi..."
4,24220935,Circulating proteins as potential biomarkers o...,dev,"{'background': '', 'conclusions': 'Our finding..."
...,...,...,...,...
19990,26521572,[Clinical efficacy on mental retardation in th...,train,"{'background': '', 'conclusions': 'The simulta..."
19991,26521581,[Efficacy of acupuncture on pain after replant...,train,"{'background': '', 'conclusions': 'Acupuncture..."
19992,26521582,[Clinical observation of Erlong Xizhu acupunct...,train,"{'background': '', 'conclusions': 'The clinica..."
19993,26521589,[Impacts on oxidative stress in the patients w...,train,"{'background': '', 'conclusions': 'EA at Neigu..."
19994,26529159,Efavirenz-Based Antiretroviral Therapy Among N...,train,{'background': 'clinicaltrials.gov Identifier ...

In [2]:
# Visualização dos dados de entrada
import pandas as pd
arq = './saidas/saida_pubmed_prof.parquet'
df = pd.read_parquet(arq)

df

          chave resumo                                           resposta erro
0      24219891     {}  {"background": "", "conclusions": "Temporary h...
1      24220044     {}  {"background": "", "conclusions": "Training in...
2      24220504     {}  {"background": "Osteoarthritis is a relatively...
3      24220704     {}  {"background": "", "conclusions": "Age-specifi...
4      24220935     {}  {"background": "", "conclusions": "Our finding...
...         ...    ...                                                ...  ...
19990  26521572     {}  {"background": "", "conclusions": "The simulta...
19991  26521581     {}  {"background": "", "conclusions": "Acupuncture...
19992  26521582     {}  {"background": "", "conclusions": "The clinica...
19993  26521589     {}  {"background": "", "conclusions": "EA at Neigu...
19994  26529159     {}  {"background": "clinicaltrials.gov Identifier ...

[19995 rows x 4 columns]

In [3]:
from util_pubmed import enrich_abstract
enrich_abstract(24228747)

Env encontrado em ../../src/.env

{'pmid': '24228747',
 'titulo': 'The spinal stenosis pedometer and nutrition lifestyle intervention (SSPANLI) randomized controlled trial protocol.',
 'palavras_chave': [],
 'journal': 'BMC musculoskeletal disorders',
 'data_publicacao': '2013-Nov'}